### ISSUE TITLE
Fix the indentation to 2 spaces

### ISSUE THREAD

**Issue by limonte** [VarXIsNotEqualY/GetRepos#1]
> Any fool can write code that a computer can understand. Good programmers write code that humans can understand.

Here's why indentation is important for humans, compare:

```js
for (var x = 0; x < 100; x++) {
  if (x % 2 == 0) {
     console.log(x);
     console.log(" is even");
  } else {
     console.log(x);
     console.log(" is odd");
  }
}
```

and

```js
for (var x = 0; x < 100; x++) {
if (x % 2 == 0) {
console.log(x);
console.log(" is even");
} else {
console.log(x);
console.log(" is odd");
}
}
```

The first code is much easier to read.

The standard indentation for JS/CSS/HTML is 2 spaces.

**Comment by limonte** [comment]
Indentation isn't fixed. The commit message of https://github.com/VarXIsNotEqualY/GetRepos/commit/2c1a62ddd38c48b4dff660dc65b27295409d5f70 should close #3, not #1

**Comment by limonte** [comment]
Reopen this issue.

**Comment by VarXIsNotEqualY** [comment]
I've changed some lines. Is my code now readable or I need to do something with it.

**Comment by limonte** [comment]
Better, but still not quite perfect.

There's the automated tool which will help you: https://standardjs.com/demo.html

Copy your JS there and click the "Correct errors" button and you'll get the properly formatted code.
